[package]
name = "fancy-ip"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

[features]
default = ["std"]
std = []

[dependencies]
# Used to emit warnings and error in the compiler logs
proc-macro-error = { version = "1", default-features = false }
litrs = "0.4.0"